#!/bin/bash
set +x

configurar() {
    local f=/etc/hosts

    grep -q "^$1.*$2" $f || { echo -e "$1\t$2" | sudo tee -a $f > /dev/null; }
}

if [ "$1" -a "$2" ]
then
  configurar $1 $2
else
  configurar 172.17.6.81 dc1
  configurar 172.17.6.82 dc2
  configurar 172.17.6.83 hc1
  configurar 172.17.6.84 hc2
fi
