#!/bin/bash

BASE_DIR=${BASE_DIR:-/vagrant}
SCRIPTS=${SCRIPTS:-$BASE_DIR/scripts}

$SCRIPTS/restaurar-cache-de-pacotes
$SCRIPTS/atualizar-e-instalar-pacotes
$SCRIPTS/configurar-hosts
$SCRIPTS/salvar-cache-de-pacotes
