[[sobre-esta-documentacao]]
= Esta documentação

[[sobre-esta-documentacao-objetivo]]
== Objetivo

Esta documentação tem o objetivo de demonstrar o uso dos scripts do projeto.
E, ela restringe-se a esse objetivo.
Sendo assim, com relação ao público esperado na leitura deste documento, assume-se que:

. Ele já tenha experiência no uso de comandos executados num shell {Bash}, em nível intermediário.
. Ele já possua conhecimentos e experiência em {JBossEAP}, particularmente em ambiente {RHEL}, em nível intermediário.

Para adquirir o conhecimento e a experiência necesssárias para um melhor entendimento deste documento, nos assuntos apontados acima, é recomendada a participação em {uri-rh-training}[treinamentos oficiais da Red Hat] ou equivalentes.

== Formato

Este documento é produzido na forma de um tutorial. Nele executamos <<demonstracoes-de-funcionamento,demonstrações que explicam o funcionamento dos scripts deste projeto>>.
Em algumas demonstrações, exercícios são propostos para fixar conteúdo já apresentado em momentos anteriores.
As <<solucoes-de-exercicios,soluções>> para esses exercícios estão disponíveis ao final deste documento.

Criada através da ferramenta {uri-asciidoctor}[Asciidoctor] (muito utilizada em vários projetos da {RedHat}), esta documentação evolui da mesma maneira que o código deste projeto.

ifdef::backend-html5[]
[NOTE]
====
Ela também pode ser {uri-jboss-domain-mode-scripts-site-docs-pt-br}/jboss-domain-mode-scripts.pdf[baixada e lida em formato PDF].
====
endif::[]

ifndef::backend-html5[]
[NOTE]
====
Ela também pode visualizada online, através de um acesso ao endereço {uri-jboss-domain-mode-scripts-site-docs-pt-br}.
====
endif::[]

Os fontes em desenvolvimento deste documento estão no mesmo {uri-jboss-domain-mode-scripts}[repositório] que o projeto, no diretório {docs-pt-br}.
Dessa forma, eles também são tratados como código e podem ter sua evolução visualizada através do {GitHub}.
Assim como realizado no desenvolvimento de qualquer software gerenciado por esta ferramenta.
