#!/bin/bash
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

./jboss-dependencies-install
./jboss-jdk-install
[ -d "$INSTALLERS_DIR/$JBOSS_DIR" ] || ./jboss-extract
./jboss-install
./jboss-firewall-configure
