#!/bin/bash
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

d=$JBOSS_INSTALL_DIR/$JBOSS_DIR
echo "Configuring $d files ..."
cd "$d"

f=bin/domain.conf
case $JBOSS_TYPE in
  master) f_patch=bin/domain.conf.master.patch;;
  backup|slave) f_patch=bin/domain.conf.slave.patch;;
esac
echo "  Patching $f with $f_patch ..."
patch $f < $f_patch > /dev/null

echo "  Configuring JBOSS variables in $f ..."
echo "    JBOSS_BIND_ADDRESS_MANAGEMENT=$JBOSS_BIND_ADDRESS_MANAGEMENT"
echo "    JBOSS_BIND_ADDRESS=$JBOSS_BIND_ADDRESS"
echo "    JBOSS_DOMAIN_MASTER_ADDRESS=$JBOSS_DOMAIN_MASTER_ADDRESS"
echo "    JBOSS_DOMAIN_BACKUP_ADDRESS=$JBOSS_DOMAIN_BACKUP_ADDRESS"
sed -i "
  s/JBOSS_BIND_ADDRESS_MANAGEMENT/$JBOSS_BIND_ADDRESS_MANAGEMENT/g ;
  s/JBOSS_BIND_ADDRESS/$JBOSS_BIND_ADDRESS/g ;
  s/JBOSS_DOMAIN_MASTER_ADDRESS/$JBOSS_DOMAIN_MASTER_ADDRESS/g ;
  s/JBOSS_DOMAIN_BACKUP_ADDRESS/$JBOSS_DOMAIN_BACKUP_ADDRESS/g
" $f

f=domain/configuration/$JBOSS_HOST_CONFIG
if [ "$JBOSS_SERVER_CONFIG" ]
then
  f_patch=domain/configuration/$JBOSS_HOST_CONFIG.$JBOSS_SERVER_CONFIG.patch
else
  f_patch=domain/configuration/$JBOSS_HOST_CONFIG.patch
fi

if [ -f "$f_patch" ]
then
  echo "  Patching $f with $f_patch ..."
  patch $f < $f_patch > /dev/null
else
  echo "  Warning: file $f_patch not found!"
fi

JBOSS_ADMIN_PASSWORD_BASE64=`echo -n $JBOSS_ADMIN_PASSWORD|base64`
echo "  Configuring JBOSS variables in $f ..."
echo "    JBOSS_HOST=$JBOSS_HOST"
echo "    JBOSS_ADMIN_USER=$JBOSS_ADMIN_USER"
echo "    JBOSS_ADMIN_PASSWORD_BASE64=$JBOSS_ADMIN_PASSWORD_BASE64"
sed -i "
  s/JBOSS_ADMIN_USER/$JBOSS_ADMIN_USER/g ;
  s/JBOSS_ADMIN_PASSWORD_BASE64/$JBOSS_ADMIN_PASSWORD_BASE64/g ;
  s/JBOSS_HOST/$JBOSS_HOST/g
" $f
