#!/bin/bash
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

if ! grep -q $JBOSS_GROUP /etc/group
then
  groupadd -r $JBOSS_GROUP && echo "JBOSS_GROUP ($JBOSS_GROUP) created!"
else
  echo "JBOSS_GROUP ($JBOSS_GROUP) already created!"
fi
