#!/bin/bash
BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

for port in 9990 9999 8080 8443
do
  firewall-cmd --zone=public --add-port=$port/tcp --permanent
done
firewall-cmd --reload
