#!/bin/bash

isRunning() {
  local machine=$1
  local status=/tmp/vagrant-status.$machine.$$

  if ! [ "$machine" ]
  then
    echo "Machine not specified!"
    return 1
  fi

  if ! [ -f "$status" ]
  then
    vagrant status $machine > "$status"
  fi

  grep -q "^$machine.*running" "$status"
}
