[[demo-1]]
= Demo 1: instalação de um DC e um HC

Nesta demonstração são apresentados os passos necessários para a instalação de um DC (`dc1`) e de um HC (`hc1`).
Nenhuma instância jboss (`server`) é criada.

== Geração do pacote de instalação (jboss-installer.tar.gz)

A construção do pacote `jboss-installer.tar.gz` é realizada pelo script {jboss-installer-create}:

[source,bash]
----
./jboss-installer.create
----

== Criação/inicialização dos servidores

O Vagrant lerá o conteúdo do arquivo link:{basedir}/demos/l/Vagrantfile[Vagrantfile] para criar e provisionar as duas máquinas desta demonstração. Esse aruqivo deverá ser copiado para o diretório `demos`:

----
cd demos
cp 1/Vagrantfile .
vagrant up
cd ..
----

[[demo-1-instalacao-dc]]
== Instalação e inicialização do DC

A cópia do conteúdo do pacote (`jboss-installer.tar.gz`) para o servidor é realizada pelo script {jboss-installer-install}:

[source,bash]
----
SSH_PORT=2222 SERVER=localhost ./jboss-installer.install
----

[NOTE]
====
Na execução do script acima será solicitada a senha do usuário `root` (da máquina `dc1`).
Informe: `vagrant`.
Por padrão, as `boxes` de base criadas com o `vagrant` utilizam essa senha.
====

Instalação do jboss:

[source,bash]
----
ssh -p 2222 root@localhost /opt/rh/jboss-installer/scripts/install
----

[NOTE]
====
A execução do comando acima demonstra como o script {install} é executado. Esse script é responsável, <<instalacao-completa,como já citado>>, pela instalação completa do ambiente de execução do JBoss.
====

Inicialização do jboss:

[source,bash]
----
ssh -p 2222 root@localhost service jboss-as-domain start
----

[NOTE]
====
O comando acima também poderia ser substituído pela execução do script {jboss-start}.
Este seria o comando equivalente:

[source,bash]
----
ssh -p 2222 root@localhost /opt/rh/jboss-installers/scripts/jboss-start
----
====

Visualização do log jboss:

[source,bash]
----
ssh -p 2222 root@localhost tail -f /var/log/jboss-as/console.log
----

[NOTE]
====
O comando acima também poderia ser substituído pela execução do script {jboss-tailf}.
Este seria o comando equivalente:

[source,bash]
----
ssh -p 2222 root@localhost /opt/rh/jboss-installers/scripts/jboss-tailf
----
====

[[demo-1-instalacao-hc]]
== Instalação e inicialização do HC

Cópia do conteúdo do pacote (`jboss-installer.tar.gz`) para o servidor:

[source,bash]
----
SSH_PORT=2200 SERVER=localhost ./jboss-installer.install
----

[[minimizacao-de-dedadas]]Minimização de dedadas no teclado ( icon:smile-o[] ):

[source,bash]
----
scripts=/opt/rh/jboss-installer/scripts
alias hc1ssh='ssh -p 2200 root@localhost'
----

Instalação do jboss:

[source,bash]
----
hc1ssh $scripts/install
----

Inicialização do jboss:

[source,bash]
----
hc1ssh $scripts/jboss-start
----

Visualização do log jboss:

[source,bash]
----
hc1ssh $scripts/jboss-tailf
----

== Verificação de funcionamento do ambiente

Abra o browser em http://dc1:9990.
Logue-se com o usuário `admin` e a senha `jbAdmin@123!`.
Acesse a aba `Domain` e verifique se o `hc1` está registrado na lista de hosts.
